---
title: "Milk intake and stroke mortality in the Japan Collaborative Cohort Study - a Bayesian survival analysis"
output: word_document
bibliography: ../Paperfolder/milk.bib 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Abstract: 

  The aim was to further examine the relationship between milk intake and stroke mortality among the Japanese population. We used data from the Japan Collaborative Cohort Study to estimate the posterior acceleration factors (AF) as well as the hazard ratios (HR) comparing individuals with different milk intake frequencies against those who never consumed milk at the study baseline. These estimations were computed through a series of Bayesian survival models that employed a Markov Chain Monte Carlo simulation process. 100000 posterior samples for each individual were generated separately through four independent chains after model convergency were confirmed. Posterior probabilites that daily milk consumers had lower hazard or delayed mortality from strokes compared to non-consumers was 99.0% and 78.0% for men and women, respectively. Accordingly, the estimated posterior means of AF and HR for daily milk consumers were 0.88 (95% Credible Interval, CrI: 0.81, 0.96) and 0.80 (95% CrI: 0.69, 0.93) for men and 0.97 (95% CrI: 0.88, 1.10) and 0.95 (95% CrI: 0.80, 1.17) for women.

keywords: 
  milk intake; mortality; stroke; Bayesian survival anlysis; time-to-event data; JACC study 
  
  
  

# Introduction

Dairy food, especially milk has been recommended to reduce stroke risk by nearly 7% for each 200 g increment of daily consumption [@DeGoede2016]. More intuitive interpretation for a decreasing risk would be possible if we were able to compute the exact probability for people who had milk intake may had lower hazard of dying from stroke compared with those who never drank milk at all. For general public/media reporting, concept of hazard in epidemiological studies could still sometimes be challenging to be understood or misinterpreted since hazard is formally defined as the probability of the occurrence of an event at a given time point [@collett2015modelling]. Usually, authors of epidemiological papers would tend to use "risk" instead of "hazard" or interchangeably. However, it would still possibly be mixed up with "risk" that only contain pure meaning of "probability of an event" without redefining a point or a period of time in cross-sectional settings. For better understanding and interpretation of the findings from data that researchers endeavored to collect, statistical literature have provided plenty of choices that could help us better communicate with each other. Another approach of comparing the time-to-event survival probabilities between different groups would be to model the time before observing an event rather than the hazard which always required the assumption of a proportional hazard to be met. Accelerated failure time models are among these convenient tools that would avoid worrying about the assumption of proportional hazard and directly showing how faster/slower one individual in an exposure group might have an event compared to others among different exposure groups [@Wei1992]. 

Our aim was to overcome these potential pitfalls, avoid misunderstanding, and provide a more straightforward answer to the main research question that whether someone answered he/she drank milk at the baseline of study had lower hazard of dying from stroke compared with his/her counterparts who said they never consumed milk. If the answer to the primary objective was yes, then the probabilities that individuals with different frequencies of milk intake may had lower hazard compared with those who never drank milk were calculated through a Markov Chain Monte Carlo (MCMC) simulation process. A Bayesian survival analysis method was applied on an existing database and through which, we also provided estimates about whether drinking milk could delay or slow down the speed towards a mortality from stroke event from happening after controlling for the other potential confounders. 



# Materials and Methods

## The database

We used data from the Japan Collaborative Cohort (JACC) study, which was sponsored by the Ministry of Education, Sports, Science, and Technology of Japan. Sampling methods and details about the JACC study have been described extensively in the literature [@Ohno2001; @Tamakoshi2005; @Tamakoshi2013]. Participants of the JACC study completed self-administered questionnaires about their lifestyles, food intake (food frequency questionnaire, FFQ), and medical histories of cardiovascular disease or cancer. In the final follow-up of the JACC study, data from a total of 110585 individuals (46395 men and 64190 women) were successfully retained for the current analysis. We further excluded samples if they meet one of the following criteria: 1) with any disease history of stroke, cancer, myocardial infarction, ischemic heart disease, or other types heart disease (n = 6655, 2931 men and 3724 women); 2) did not answer the question regarding their milk consumption in the baseline FFQ survey (n = 9545, 3593 men and 5952 women). Finally, 94385 (39386 men and 54999 women) are left in the database. The study design and informed consent procedure were approved by the Ethics Review Committee of Nagoya University School of Medicine.

## Exposure and the outcome of interest

Frequency of milk intake during the preceding year of the baseline was assessed by FFQ from "never", "1-2 times/month", "1-2 times/week", "3-4 times/week", and "Almost daily". The exact amount of milk consumption was difficult to assess here. However, good reproducibility and validity were confirmed previously (Spearman rank correlation coefficient between milk intake frequency and weighed dietary record for 12 days was 0.65) [@Date2005].

The causes and date of death were obtained from death certificates and were systematically reviewed. The follow-up period was defined as from the time of the baseline survey was completed, which was between 1988-1990, until the end of 2009 (administrative censor), or the date when move-out of study area, or the date of death from stroke recorded, whichever occurred first. Other causes of death were treated as censored and assumed not informative. The causes of death were coded by the 10th Revision of the International Statistical Classification of Diseases and Related Health Problems (ICD-10), therefore stroke was defined as I60-I69. We further classified these deaths into hemorrhagic stroke (I60, I61 and I62) or cerebral infarction (I63) when subtypes of stroke in their death certificates were available. 

## Statistical approach

We calculated sex-specific means (standard deviation, sd) and proportion of selected baseline characteristics according to the frequency of milk intake. Overall difference across the milk intake groups were tested by either analysis of variance for continuous variables or $\chi^2$ test for categorical variables. 

Full parametric proportional hazard models under Bayesian framework with Weibull distribution were fitted using Just Another Gibbs Sampler (JAGS) program [@Plummer2003] version 4.3.0 in R version 4.0.1 [@RCT2020]. JAGS program is similar to the OpenBUGS [@Lunn2009] project that uses a Gibbs sampling engine for MCMC simulation. In the current analysis, we specified non-informative prior distributions for each of the parameters in our models ($\beta_n \sim N(0, 1000)$, and $\kappa_{\text{shape}} \sim \Gamma(0.001, 0.001)$). The Brooks-Gelman-Rubin diagnostic [@Brooks1998] was used to refine the approximate point of convergence, the point when the ratio of the chains is stable around 1 and the within and between chain variability start to reach stability was visually checked. The auto-correlation tool further identified if convergence has been achieved or if a high degree of auto-correlation exists in the sample. Then, the number of iterations discarded as ‘burn-in’ was chosen. All models had a posterior sample size of 100000 from four separated chains with a "burn-in" of 2500 iterations. Posterior means (sd) and 95% Credible Intervals (CrI) of the estimated hazard ratios (HRs) as well as acceleration factors (AFs) were presented for each category of milk intake frequency taking the "never" category as the reference. Posterior probabilities that the estimated hazard of dying from stroke for the milk intake for frequency that higher or equal to "1-2 times/month" is smaller compared with those who chose "never" to their milk intake frequency were calculated as $P(\text{HR} < 1)$. 

The parametric forms of the models fitted in the Bayesian survival analyses included three models: 1) the crude model, 2) the age-centered adjusted model, 3) and a model further adjusted for potential confounders which includes: age (centered, continuous), smoking habit (never, current, former), alcohol intake (never or past, $<$ 4 times/week, Daily), body mass index ($<$ 18.5, $\geq$ 18.5 and $<$ 25, $\geq$ 25 and $<$ 30, $\geq$ 30 kg/m$^2$), history of hypertension, diabetes, kidney/liver diseases (yes/no), exercise (more than 1 hour/week, yes/no), sleep duration ($<$ 7, $\geq$ 7 and $<$ 8, $\geq$ 8 and $<$ 9, $\geq$ 9, hours), coffee intake (never, $<$ 3-4 times/week, almost daily), education level (attended school till age 18, yes/no)


# Results

The total follow-up was 1555073 person-years (median = 19.3 years), during which 2675 death from stroke was confirmed (1352 men and 1323 women). Among these stroke mortality, 952 were hemorrhagic stroke (432 men and 520 women), and 957 were cerebral infarction (520 men and 437 women). 

As listed in **Table 1**, compared with those who chose "never" as their milk intake frequency at baseline, milk drinkers were less likely to be a current smoker or a daily alcohol consumer in both men and women. Furthermore, people consumed milk more than 1-2 times/month were more likely to be a daily consumers of vegetable, fruit  as well as coffee, and more likely to join exercise more than 1 hour/week among both sex.

Detailed results from the Bayesian survival models (crude, age-adjusted and multivariable-adjusted) according to the frequency of milk intake separated by sex are listed in **Table 2** (men) and **Table 3** (women). Compared to those who never had milk, both men and women had slower speed and lower hazard of dying from total stroke in crude models. Velocities that milk consumers dying from stroke is slower by a crude acceleration factor (AF) between 0.79 (sd = 0.05; 95% CrI: 0.74, 0.90) and 0.93 (sd = 0.04; 95% CrI: 0.85, 1.02) compared with non-consumers. Chances that the posterior crude HRs were estimated to be lower than 1 for those who had at least 1-2 times/month was higher than 86.5% in men and greater than 94.6% in women. However, lower hazard and delayed time-to-event was observed to remain after age or multivariable adjustment only among daily male milk consumers. Specifically, the mean (sd; 95% CrI) of posterior multivariable-adjusted AF and HR for daily male consumers of milk were 0.88 (sd = 0.05; 95% CrI: 0.81, 0.96) and 0.80 (sd = 0.07; 95% CrI: 0.69, 0.93) with a probability of 99.0% to be smaller than the null value (=1). Daily female milk consumers had posterior AFs and HRs that was distributed with means of 0.97 (sd = 0.09; 95% CrI: 0.88, 1.10) and 0.95 (sd = 0.12; 95% CrI: 0.80, 1.17) which had about 78.0% of chance that their HRs could be smaller than 1. 

Posterior distributions of AFs and HRs for mortality from hemorrhagic stroke were found to contain the null value for either men or women among all fitted models. In contrast, men who had milk intake frequency higher than 1-2 times/week were found to be associated with averagely 17%-20% slower velocity or 28%-39% lower hazard of dying from cerebral infarction compared to men who never drank milk (Model 2 in \textbf{Table \ref{tab:tab2}}). Probability that the posterior HRs distributed below the null value was greater or equal to 97.5%. No evidence was found about the associations between milk intake and hazard of cerebral infarction mortality among women.
 
# Discussion

<!-- - summary of the finding -->

In the JACC study cohort, our analysis showed that men in Japan who consumed milk almost daily had lower hazard of dying from stroke especially from cerebral infarction. Our evidence also suggested that stroke mortality events were delayed among Japanese male daily milk consumers compared with non-consumers.

<!-- - comparison with previous meta-analyses -->
These findings are in line with our previous report [@wang_milk_2015] as well as other studies conducted in East Asian populations [@umesawa2008dietary;@kondo2013consumption;@ozawa2017dietary;@sauvaget2003intake;@Talaei_2016]. Moreover, we have further updated with more comprehensive and straightforward evidence about whether and how certain the data had shown about daily consumption of milk is contributing to a postponed stroke (mostly cerebral infarction) mortality event among Japanese men. A recent dose-response meta-analysis of 18 prospective cohort studies had also shown a similar negative association [@DeGoede2016] between milk consumption and risk of stroke. The same meta-analysis also reported a greater reduction of risk of stroke (18%) for East Asian population in contrast with the 7% less risk in the pooled overall finding for all populations combined. Benefits of increased milk intake might be particularly noticeable in East Asian countries where strokes are relatively more common, and milk consumption is much lower than those studies conducted among European or American populations [@dehghan2018association]. 
<!-- - potential biological reasons -->

Possible reasons for a protective effect of milk consumption against stroke could be interpreted as such an association may be mediated by its content in calcium, magnesium, potassium, and other bioactive compounds, as recommended by @Iacoviello2018. Apart from the inorganic minerals in milk that would be helpful with health effects, recent studies on animal models also indicated key evidence that stroke-associated morbidity was delayed in stroke-prone rats who were fed with milk-protein enriched diets [@Chiba2012;@singh2016diets]. More precisely, @Singh2020 found that whey protein and its components lactalbumin and lactoferrin improved energy balance and glycemic control against the onset of neurological deficits associated with stroke. Bioactive peptides from milk proteins were also responsible for limitation of thrombosis [@tokajuk2019whey] through their angiotensin convertase enzyme inhibitory potential, which might partly explain why the effect was found mainly for mortality from cerebral infarction in the current study. 


<!-- - strength and limitation of current study -->
Some limitations here are worth mentioning. First, although our object was not to answer which type of milk is protective, but if such information were somehow available in the JACC study database, more detailed comparison or stratification would have been possible. Second, despite reasonable validity of FFQ in the JACC study cohort was assessed and confirmed, measurement errors are inevitable. Therefore, we did not try to compute the amount of consumption by multiplying an average volume per occasion with the frequency of intake since the random error might be exaggerated and the observed associations may have attenuated. Strengths of our analyses included that we have transformed the research questions to more transparent ones that is easier for interpretation. Direct probabilities that daily milk intake is associated with lower hazard or delayed stroke mortality event were provided here after thorough computer simulation. 

In conclusion, the JACC study database has provided evidence that Japanese men who consumed milk daily had lower hazard of dying from stroke especially cerebral infarction compared with their counterparts who never consumed milk. Time before an event of stroke mortality occurred were slowed down and delayed among those who drank milk regularly.
